backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    summary: "{{title | upper}} - {{date | date('YYYY-MM-DD')}} – {{body | truncate(20, '***')}}"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", min: 1, allow_ad: true }
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - {
              label: "Cover Image",
              name: "image",
              widget: "image",
              required: false,
            }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              allow_multiple: false,
              required: false,
            }
      - { label: "Body", name: "body", widget: "markdown" }
